# Generated by Django 5.1.7 on 2025-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_fluid', '0002_initial_fluids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incompressiblemixturefluid',
            options={'verbose_name': 'Fluide à mélange', 'verbose_name_plural': 'Fluides à mélange'},
        ),
    ]
